"""Add author_id to Plugin model and User.plugins relationship

Revision ID: 2b306bc18b14
Revises: 8b401fe43700
Create Date: 2025-06-06 20:01:22.925771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b306bc18b14'
down_revision: Union[str, None] = '8b401fe43700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_plugins_author_id'), 'plugins', ['author_id'], unique=False)
    # Assuming the old author column was VARCHAR(128) as per original model inspection
    op.drop_column('plugins', 'author')
    op.create_foreign_key(
        'fk_plugins_author_id_users',  # Constraint name
        'plugins', 'users',
        ['author_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_plugins_author_id_users', 'plugins', type_='foreignkey')
    op.add_column('plugins', sa.Column('author', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plugins_author_id'), table_name='plugins')
    op.drop_column('plugins', 'author_id')
    # ### end Alembic commands ###
